#######################################################################################
# Book settings
title: Scientific Programming In Real Life
author: Christian Tai Udovicic
copyright: "2020"
email: cj.taiudovicic@gmail.com
logo: images/logo/logo_spirl.png
exclude: []

#######################################################################################
# Execution settings
execute:
  execute_notebooks: 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: [] # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/favicon.ico"
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : ""  # Will be displayed underneath the left navbar.
  extra_footer              : "<a href='https://cjtu.github.io'>About Christian</a>"  # Will be displayed underneath the footer.
  google_analytics_id       : "UA-111642150-3"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://cjtu.github.io/spirl"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/cjtu/spirl  # The URL to your book's repository
  path_to_book              : "/spirl"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
